# -*- coding: utf-8 -*-
"""Water potability model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gjnyojm8lmnuzzWfYAZft40U28f-lPSO

# 🌊 Water Potability Prediction Using Machine Learning

## Project Overview

Access to safe drinking water is essential for public health. This project uses Machine Learning techniques to predict whether water is potable (safe for drinking) based on various physicochemical parameters.

### Objectives

* Perform Exploratory Data Analysis (EDA)
* Handle missing values and class imbalance
* Train multiple machine learning models
* Compare model performance
* Analyze feature importance
* Predict water potability accurately

### Machine Learning Models Used

* Logistic Regression
* Random Forest Classifier
* XGBoost Classifier

### Dataset Features

The dataset contains various water quality parameters including:

* pH
* Hardness
* Solids
* Chloramines
* Sulfate
* Conductivity
* Organic Carbon
* Trihalomethanes
* Turbidity

### Target Variable

* 0 → Non-Potable Water
* 1 → Potable Water
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    roc_curve
)

from imblearn.over_sampling import SMOTE

import warnings
warnings.filterwarnings('ignore')

plt.style.use('seaborn-v0_8')
sns.set_palette("husl")

"""## Dataset Upload and Loading

The dataset is uploaded from the user's local machine and loaded into a Pandas DataFrame.
"""

from google.colab import files
import io

print("Upload water_potability.csv")
uploaded = files.upload()

filename = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[filename]))

print("Dataset Loaded Successfully")
print("Shape:", df.shape)
df.head()

"""## Dataset Information

Understanding the structure, columns, and missing values present in the dataset.
"""

print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nColumns:")
print(df.columns.tolist())

"""## Data Cleaning

Missing values are replaced using mean imputation to ensure model training is not affected by incomplete records.
"""

df.fillna(df.mean(), inplace=True)

print("Missing Values After Cleaning:")
print(df.isnull().sum())

"""## Target Variable Identification

Identify the potability column used for prediction.
"""

target_column = None

possible_targets = [
    'Potability',
    'potability',
    'Target',
    'target',
    'Class',
    'class',
    'Quality',
    'quality'
]

for col in possible_targets:
    if col in df.columns:
        target_column = col
        break

if target_column is None:
    target_column = df.columns[-1]

print("Target Variable:", target_column)

"""## Exploratory Data Analysis (EDA)

Analyze distributions, class balance, and feature behavior.
"""

print(df.describe())

print("\nTarget Distribution:")
print(df[target_column].value_counts())

print("\nTarget Ratio:")
print(df[target_column].value_counts(normalize=True))

plt.figure(figsize=(15,12))

plt.subplot(3,3,1)
df[target_column].value_counts().plot(
    kind='bar',
    color=['skyblue','lightcoral']
)

plt.title("Potability Distribution")
plt.xlabel("Potability")
plt.ylabel("Count")

feature_columns = [c for c in df.columns if c != target_column]

for i in range(min(4,len(feature_columns))):
    plt.subplot(3,3,i+2)
    df[feature_columns[i]].hist(
        bins=30,
        alpha=0.7
    )
    plt.title(feature_columns[i])

plt.tight_layout()
plt.show()

"""## Correlation Analysis

Study relationships between variables using a correlation heatmap.
"""

plt.figure(figsize=(12,8))

correlation_matrix = df.corr()

mask = np.triu(
    np.ones_like(
        correlation_matrix,
        dtype=bool
    )
)

sns.heatmap(
    correlation_matrix,
    mask=mask,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title("Feature Correlation Heatmap")
plt.show()

"""## Data Preprocessing

Prepare data for machine learning:
- Train/Test Split
- Standard Scaling
- SMOTE Oversampling
"""

X = df.drop(target_column, axis=1)
y = df[target_column]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

smote = SMOTE(random_state=42)

X_train_balanced, y_train_balanced = smote.fit_resample(
    X_train_scaled,
    y_train
)

print("Training Shape:", X_train_balanced.shape)

"""## Model Training

Train Logistic Regression, Random Forest, and XGBoost models.
"""

models = {
    "Logistic Regression":
        LogisticRegression(random_state=42),

    "Random Forest":
        RandomForestClassifier(
            n_estimators=100,
            random_state=42
        ),

    "XGBoost":
        XGBClassifier(
            random_state=42,
            eval_metric='logloss'
        )
}

results = {}

for name, model in models.items():

    model.fit(
        X_train_balanced,
        y_train_balanced
    )

    y_pred = model.predict(X_test_scaled)

    y_pred_proba = model.predict_proba(
        X_test_scaled
    )[:,1]

    results[name] = {
        'model': model,
        'accuracy': accuracy_score(y_test,y_pred),
        'precision': precision_score(y_test,y_pred),
        'recall': recall_score(y_test,y_pred),
        'f1': f1_score(y_test,y_pred),
        'roc_auc': roc_auc_score(y_test,y_pred_proba),
        'predictions': y_pred,
        'probabilities': y_pred_proba
    }

"""## Model Performance Comparison"""

results_df = pd.DataFrame({
    'Model': list(results.keys()),
    'Accuracy': [results[m]['accuracy'] for m in results],
    'Precision': [results[m]['precision'] for m in results],
    'Recall': [results[m]['recall'] for m in results],
    'F1-Score': [results[m]['f1'] for m in results],
    'ROC-AUC': [results[m]['roc_auc'] for m in results]
})

results_df

"""## ROC Curve Analysis"""

plt.figure(figsize=(8,6))

for name, result in results.items():
    fpr, tpr, _ = roc_curve(
        y_test,
        result['probabilities']
    )

    plt.plot(
        fpr,
        tpr,
        label=f"{name} (AUC={result['roc_auc']:.3f})"
    )

plt.plot([0,1],[0,1],'k--')

plt.legend()
plt.title("ROC Curve Comparison")
plt.show()

"""## 11. Feature Importance Analysis"""

rf_importance = results[
    'Random Forest'
]['model'].feature_importances_

xgb_importance = results[
    'XGBoost'
]['model'].feature_importances_

combined_importance = (
    rf_importance + xgb_importance
) / 2

feature_importance_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': combined_importance
}).sort_values(
    'Importance',
    ascending=False
)

feature_importance_df

"""##  Best Model Evaluation"""

best_model_name = max(
    results,
    key=lambda x: results[x]['f1']
)

print(best_model_name)

print(
    classification_report(
        y_test,
        results[best_model_name]['predictions']
    )
)

"""# Conclusion

The project successfully predicts water potability using Machine Learning models.

Key techniques used:

- Missing Value Imputation
- Standardization
- SMOTE Oversampling
- Logistic Regression
- Random Forest
- XGBoost

The best-performing model was selected using F1-Score and ROC-AUC metrics.

This workflow can support water quality monitoring and decision-making systems.
"""